version: 1.0.{build}

skip_tags: true
test: off
max_jobs: 1

cache:
  - C:\ProgramData\chocolatey\bin
  - C:\ProgramData\chocolatey\lib

install:
  # - cmd: SET APPVEYOR_SAVE_CACHE_ON_ERROR=true
  # - cmd: choco install mingw
  - cmd: DIR C:\ProgramData\chocolatey\lib\mingw\tools\install
  - cmd: SET PATH=C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw32\bin;%PATH%

before_build:
  - cmd: mingw32-make --version | head -1
  - cmd: g++ --version | head -1
  - cmd: 7z --help | head -3

build_script:
  - cmd: git submodule init
  - cmd: git submodule update
  - cmd: mingw32-make -j1 --keep-going

after_build:
  - cmd: IF NOT EXIST deploy MKDIR deploy
  - cmd: cd deploy
  - cmd: COPY ..\README.md .
  - cmd: COPY ..\LICENSE .
  - cmd: COPY ..\scite\bin\*.exe .
  - cmd: COPY ..\scite\bin\*.dll .
  - cmd: COPY ..\scite\bin\*.properties .
  - cmd: 7z a ..\$(appveyor_project_name)-$(appveyor_build_version).7z .

artifacts:
  - path: $(appveyor_project_name)-$(appveyor_build_version).7z

deploy:
  - provider: Environment
    name: GH
    on:
      branch: master
